=pod

=for HTML <a href="https://travis-ci.org/mdom/txtnix"><img src="https://travis-ci.org/mdom/txtnix.svg?branch=master"></a>

=for HTML <a href='https://coveralls.io/r/mdom/txtnix?branch=master'><img src='https://coveralls.io/repos/mdom/txtnix/badge.png?branch=master' alt='Coverage Status' /></a>

=head1 NAME

txtnix - Client for twtxt, the minimalist microblogging service for hackers

=head1 SYNOPSIS

  txtnix COMMAND [OPTIONS...]

  Command:
  tweet       Append a new tweet to your twtxt file.
  timeline    Retrieve your personal timeline.
  view        Show feed of given source.
  follow      Add a new source to your followings.
  unfollow    Remove an existing source from your followings.
  following   Return the list of sources you're following.
  config      Get or set config item.

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix config COMMAND [OPTIONS...]

  Command:
  edit        Edit configuration file.
  get         Get configuration option.
  set         Set configuration option.
  remove      Remove configuration option.

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix config edit [OPTIONS...]

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix config get KEY [OPTIONS...]

  Arguments:
  KEY         Configuration option to get.

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix config remove KEY [OPTIONS...]

  Arguments:
  KEY         Configuration option to remove.

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix config set KEY VALUE [OPTIONS...]

  Arguments:
  KEY         Configuration option to set.
  VALUE       Value configuration option to set to.

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix follow NICKNAME URL [OPTIONS...]

  Arguments:
  NICKNAME    Local nickname for url.
  URL         URL for follow.

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix following [OPTIONS...]

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix timeline [OPTIONS...]

  Options:
  --help           Print a help message and exit.
  --config         Specify a custom config file location.
  --cache          Cache remote twtxt files locally.
  --timeout        Maximum time requests are allowed to take.
  --pager          Use a pager to display content.
  --time-format    Format to display timestamps.
  --limit          Limit total number of shown tweets.
  --ascending      Sort timeline in ascending order.
  --descending     Sort timeline in descending order.


  txtnix tweet TEXT [OPTIONS...]

  Arguments:
  TEXT            Message to tweet.

  Options:
  --help          Print a help message and exit.
  --config        Specify a custom config file location.
  --created-at    ISO8601 datetime to use in Tweet, instead of current time.
  --twtfile       Location of your twtxt file.


  txtnix unfollow NICKNAME [OPTIONS...]

  Arguments:
  NICKNAME    Nick to unfollow.

  Options:
  --help      Print a help message and exit.
  --config    Specify a custom config file location.


  txtnix view SOURCE [OPTIONS...]

  Arguments:
  SOURCE           Source to view.

  Options:
  --help           Print a help message and exit.
  --config         Specify a custom config file location.
  --cache          Cache remote twtxt files locally.
  --timeout        Maximum time requests are allowed to take.
  --pager          Use a pager to display content.
  --time-format    Format to display timestamps.
  --limit          Limit total number of shown tweets.
  --ascending      Sort timeline in ascending order.
  --descending     Sort timeline in descending order.

=head1 DESCRIPTION

I<txtnix> is a client for the decentralised, minimalist microblogging
service for hackers L<https://github.com/buckket/twtxt>.

Until i find the time to write some documentation,
you should check the very good documentation over at
I<http://twtxt.readthedocs.org/en/latest/index.html>. Although i don't
plan to reimplement every feature identically, the configuration options
and commands should behave very similar at the moment.

=head1 COPYRIGHT AND LICENSE

Copyright 2015 Mario Domgoergen C<< <mario@domgoergen.com> >>

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see <http://www.gnu.org/licenses/>.
